#!/bin/bash
echo "this is practice file created"
echo "this is simple command to check webhook"
echo " running this line after webhook sethub has done"
echo "be careful while adding an url in webhook"
echo" hello"
echo"bye"
echo "sample line added"
echo "aks"
echo" line addition"
